### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Dandertuts** [vini2003/Black-Hole#1]
After installing both fabric api (latest version) fabric (latest version) and cloth api (latest version) I got this error message upon booting "The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'blackhole'!
Exit Code: -1"

**Comment by MinecrAftModders** [comment]
same idk why

**Comment by vini2003** [comment]
Please send the full log.

**Comment by vini2003** [comment]
Closed it is, then.
