### ISSUE TITLE
Doesn't work, kinda.

### ISSUE THREAD

**Issue by ItsMePlasticB** [vini2003/Black-Hole#3]
The black hole is invisible, I can't see it. It does work, it pulls everything in, but I can't see it.

**Comment by vini2003** [comment]
You have Sodium installed. Remove it; as this mod uses [https://github.com/Hephaestus-Dev/myron](Myron) which is incompatible with it.

Either I change my rendering, or Myron updates their model loader to work with Sodium. Funnily enough, OptiFine works in this case.

**Comment by Wachecheiro** [comment]
excellent mod, gives chills.
One question, does the black hole have a maximum tracking distance?
If I go 10,000 blocks away, does this keep haunting me?
If you have a maximum tracking distance, what would it be?
regards
