### ISSUE TITLE
Failed to Launch error

### ISSUE THREAD

**Issue by AppleMP4** [vini2003/Black-Hole#5]
I installed everything listed correctly but i get this window when i launch the mod
![failed](https://user-images.githubusercontent.com/79847968/109498301-9136c900-7a93-11eb-95c9-2ed47abc1ae6.PNG)

**Comment by Ch1216** [comment]
Are you sure you intalled fabric api 1.16?

**Comment by vini2003** [comment]
Indeed, you're missing the dependencies listed in the CurseForge page.
