### ISSUE TITLE
It says I have to get cloth config2 and I installed cloth config and all the other required mods and it still doesn't work

### ISSUE THREAD

**Issue by pokemonmaster125** [vini2003/Black-Hole#8]
the title it just won't launch when it lauches it is not the minecraft app it is fabric and it says I need cloth config2 someone please link it for me I want to try this

**Comment by vini2003** [comment]
It's likely you're using the wrong version. Download the latest version for Minecraft 1.16.5 available on CurseForge, as linked in the project page and video.
